In [ ]:
name = "Hi How are you? Starterd learning python. It's really interesting."
print(name)
name[:]

Hi How are you? Starterd learning python. It's really interesting.

"Hi How are you? Starterd learning python. It's really interesting."

In [ ]:
name[-10:-5]

'teres'

In [ ]:
name[3:12]

'How are y'

In [ ]:
name[12:3]

''

In [ ]:
name[5:6]

'w'

In [ ]:
name[-4:-12]

''

In [ ]:
name[::2]

"H o r o?Satr erigpto.I' elyitrsig"

In [ ]:
name[::-2]

'.nteen larst nhy nnaldert uyeawHi'

QUESTION 2

In [ ]:
L1 = ['a' , 'b', 20, 30, 't', 100, 300, 400, 'Happy', 'major']
print(L1)

['a', 'b', 20, 30, 't', 100, 300, 400, 'Happy', 'major']

In [ ]:
L1[:]
L1[::3]
L1[::-2]

['major', 400, 100, 30, 'b']

In [ ]:
L1[-2]

'Happy'

In [ ]:
L1[3]
type(L1[3])

int

In [ ]:
L1[5:8]

[100, 300, 400]

QUESTION 3

In [ ]:
l2 =[1,2,3,5,['a', 'b', 'work hard'],100 , 200, "Success"]
print(l2)

[1, 2, 3, 5, ['a', 'b', 'work hard'], 100, 200, 'Success']

In [ ]:
l2[4]

['a', 'b', 'work hard']

In [ ]:
l2[1:5]

[2, 3, 5, ['a', 'b', 'work hard']]

In [ ]:
l2[7]

'Success'

In [ ]:
l2[7][2]

'c'

In [ ]:
l2[7][2:]

'ccess'

In [ ]:
l2[ : 3]

[1, 2, 3]

In [ ]:
l2[3:]

[5, ['a', 'b', 'work hard'], 100, 200, 'Success']

QUESTION 4

In [ ]:
l2 =[1,2,3,5,['a', 'b', 'work hard'],100 , 200, "Success"]
l2[4][1] = 'BEE'
print(l2)

[1, 2, 3, 5, ['a', 'BEE', 'work hard'], 100, 200, 'Success']

QUESTION 5

In [ ]:
l2[4].remove('BEE')
print(l2)

[1, 2, 3, 5, ['a', 'work hard'], 100, 200, 'Success']

QUESTION 6

In [ ]:
l2.append({'insect': ['bee', 'moth'], 'bird': ['parrot', 'sparrow']})
print(l2)

[1, 2, 3, 5, ['a', 'work hard'], 100, 200, 'Success', {'insect': ['bee', 'moth'], 'bird': ['parrot', 'sparrow']}]

In [ ]:
print(l2)

[1, 2, 3, 5, ['a', 'work hard'], 100, 200, 'Success', {'insect': ['bee', 'moth'], 'bird': ['parrot', 'sparrow']}]

QUESTION 7

In [ ]:
l2[-1]['insect']

['bee', 'moth']

QUESTION 8

In [ ]:
d1 = {'a':10, 'b':20, 'c' : 30}

In [ ]:
print(d1)

{'a': 10, 'b': 20, 'c': 30}

In [ ]:
#add the d1 at 2nd position of l2
l1.append(l2[2])

In [ ]:
l1.pop()  # removes the last element (3)

3

In [ ]:
d1 = {'insect': ['bee', 'moth'], 'bird': ['parrot', 'sparrow']}
l2.insert(1, d1)

QUESTION 9

In [ ]:
#9. Based on new l2 created here extract the value 10 from l2 dictionary.
my_dict = l2[1]  # {'insect': ['bee', 'moth'], 'bird': ['parrot', 'sparrow']}

In [ ]:
my_dict['insect']   # ['bee', 'moth']

['bee', 'moth']

In [ ]:
my_dict['bird']     # ['parrot', 'sparrow']

['parrot', 'sparrow']

QUESTION 10

In [ ]:
L2 =[1,2,3,5, (90,40,50,10), 'Python', 400 ,['a', 'b', 'work hard'],100 , 200, "Success", (200,300, "Hundreds")]
print(L2)

[1, 2, 3, 5, (90, 40, 50, 10), 'Python', 400, ['a', 'b', 'work hard'], 100, 200, 'Success', (200, 300, 'Hundreds')]

In [ ]:
L2[4][2]

50

In [ ]:
L2[5][:]

'Python'

In [ ]:
# L2[2][:] # This caused a TypeError: 'int' object is not subscriptable

In [ ]:
L2[1:5]

[2, 3, 5, (90, 40, 50, 10)]

In [ ]:
L2[5]

'Python'

In [ ]:
L2[5][3:-1]

'ho'

In [ ]:
L2[-1]

(200, 300, 'Hundreds')

In [ ]:
# L2[-4, -3] # This caused a TypeError: list indices must be integers or slices, not tuple
L2[-4]
# or L2[-4:-3] for slicing

100

In [ ]:
L2[-4: -10]

[]

In [ ]:
L2[7][2]

'work hard'

In [ ]:
L2[-7][2:]

'thon'

In [ ]:
L2[ :- 3]

[1, 2, 3, 5, (90, 40, 50, 10), 'Python', 400, ['a', 'b', 'work hard'], 100]

In [ ]:
L2[-3:]

[200, 'Success', (200, 300, 'Hundreds')]

QUESTION 11

In [ ]:
#11. Ask user to enter the marks and define if the user got distinction, first class, second class, pass, Fails .If marks are more than 80 output must be “You got distinction”For marks more than 60 output must be “You got First class” Marks more than 40 will display “You got second class” Marks more than or equal to 35 “PASS” Otherwise Fail

marks = float(input("enter your marks "))

if marks > 100:
    print("percentage should be 100 or below")
elif marks < 0:
    print("should be above 0")
elif marks > 80:
    print("you got distinction")
elif marks > 60:
    print("you got first class")
elif marks > 40:
    print("you got second class")
elif marks > 35:
    print("pass")
else:
    print("failed in exam")

enter your marks 20
failed in exam

question 12

In [ ]:
#12. Ask user to enter information about salary of the employee per year and rating received as A, B, C, D

#If salary upto 5 lpa then increament based on ratings are A = 16% , B=12%, C= 10%, D=6%

#If salary upto 10 lpa then increament based on ratings are A = 14% , B=10%, C= 8%, D=6%

#If salary upto 15 lpa then increament based on ratings are A = 8% , B=6%, C= 4%, D = no increment

#If salary upto 23 lpa then increament based on ratings are A = 7% , B=5%, C= 4%, D=no

In [ ]:
salary = float(input("Enter your salary per year(in LPA): "))
rating = input("Enter your rating (A/B/C/D):").upper()

#increment percentages for each salary slab
if salary <= 5:
    increments = {'A': 16, 'B': 12, 'C': 10, 'D': 6}
elif salary <= 10:
    increments = {'A': 14, 'B': 10, 'C': 8, 'D': 6}
elif salary <= 15:
    increments = {'A': 8, 'B': 6, 'C': 4, 'D': 0}
elif salary <= 23:
    increments = {'A': 7, 'B': 5, 'C': 4, 'D': 0}
else:
    increments = {'A': 0, 'B': 0, 'C': 0, 'D': 0}

# Get increment percentage from the dictionary
increment = increments.get(rating, 0)

# Calculate new salary
new_salary = salary + (salary * increment / 100)

# Print result
print(f"Original Salary: {salary} LPA")
print(f"Rating: {rating}")
print(f"Increment: {increment}%")
print(f"New Salary: {new_salary} LPA")

Enter your salary per year (in LPA): 5
Enter your rating (A/B/C/D): b
Original Salary: 5.0 LPA
Rating: B
Increment: 12%
New Salary: 5.6 LPA

13. Ask user to opt for courses for master degree based on the following

L1 = [“HR”, “Finance”, “Marketing”, “DS”]

Based on above subject there are two different streams. For example- HR is having HR core and HR analytics and Marketing is having core and Marketing analytics. Analytics is the optional subject and having added extra fees. DS is not having analytics.

If fees for L1 is 2 lakhs for each course core subject having the same fees but analytics subject having 10% extra on 2 lakhs.

If student opts for hostel then 2 lakhs per year is added. For food monthly 2000 .

Transportation charges 13000 per semester. Calculate the total annual cost based on selected service.

User will enter values as subject, analytics(Y/N), Hostel (Y/N), food(How many months?), Transportation(semester/annual)

In [ ]:
#using if else
L1 = ["HR", "Finance", "Marketing", "DS"]

#base fees
BASE_FEE = 200000            # 2 lakhs
ANALYTICS_EXTRA = 0.10       # 10%
HOSTEL_FEE = 200000          # per year
FOOD_PER_MONTH = 2000
TRANSPORT_PER_SEM = 13000

#user inputs
subject = input("Enter subject (HR/Finance/Marketing/DS):").strip()
analytics = input("Analytics? (Y/N):").strip().upper()
hostel = input("Hostel? (Y/N): ").strip().upper()
food_months = int(input("Food for how many months?:"))
transport = input("Transportation (semester/annual):").strip().lower()

if subject not in L1:
    print("Invalid subject selected")
    exit()

total_fee = BASE_FEE

if analytics == "Y" and subject != "DS":
    total_fee += BASE_FEE * ANALYTICS_EXTRA

if hostel == "Y":
    total_fee += HOSTEL_FEE

total_fee += food_months * FOOD_PER_MONTH

if transport == "semester":
    total_fee += TRANSPORT_PER_SEM * 2   #2 semesters per year
elif transport == "annual":
    total_fee += TRANSPORT_PER_SEM * 2
else:
    print("Invalid transportation option")
    exit()

print("\n----- Fee Breakdown ----")
print(f"Subject: {subject}")
print(f"Total Annual Cost in Rs:{int(total_fee)}")

Enter subject (HR/Finance/Marketing/DS): HR
Analytics? (Y/N): Y
Hostel? (Y/N): Y
Food for how many months?: 2
Transportation (semester/annual): Semester

----- Fee Breakdown -----
Subject: HR
Total Annual Cost: ₹450000

solved using sql-lite

In [ ]:
import sqlite3

#SQLite DB
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

#Create tables
cursor.execute("""
CREATE TABLE fee_structure (
    subject TEXT PRIMARY KEY,
    base_fee INTEGER,
    analytics_extra REAL
);
""")

cursor.execute("""
CREATE TABLE hostel_food_transport (
    hostel_fee INTEGER,
    food_per_month INTEGER,
    transport_per_sem INTEGER
);
""")

#Insert fee structure
cursor.executemany("""
INSERT INTO fee_structure VALUES (?, ?, ?);
""", [
    ("HR",      200000, 0.10),
    ("Finance", 200000, 0.10),
    ("Marketing", 200000, 0.10),
    ("DS",      200000, 0.00)
])

cursor.execute("""
INSERT INTO hostel_food_transport VALUES (200000, 2000, 13000);
""")

conn.commit()

In [ ]:
subject = input("Enter subject (HR/Finance/Marketing/DS): ").strip()
analytics = input("Analytics? (Y/N): ").strip().upper()
hostel = input("Hostel? (Y/N): ").strip().upper()
food_months = int(input("Food for how many months?: "))
transport = input("Transportation (semester/annual): ").strip().lower()

Enter subject (HR/Finance/Marketing/DS): HR
Analytics? (Y/N): Y
Hostel? (Y/N): Y
Food for how many months?: 1
Transportation (semester/annual): semester

In [ ]:
subject = input("Enter subject (HR/Finance/Marketing/DS): ").strip()
analytics = input("Analytics? (Y/N): ").strip().upper()
hostel = input("Hostel? (Y/N): ").strip().upper()
food_months = int(input("Food for how many months?: "))
transport = input("Transportation (semester/annual): ").strip().lower()

Enter subject (HR/Finance/Marketing/DS): HR
Analytics? (Y/N): Y
Hostel? (Y/N): U
Food for how many months?: 3
Transportation (semester/annual): semester

In [ ]:
query = """
SELECT
    f.subject,
    f.base_fee
    + CASE
        WHEN ? = 'Y' AND f.subject != 'DS'
        THEN f.base_fee * f.analytics_extra
        ELSE 0
      END
    + CASE
        WHEN ? = 'Y' THEN h.hostel_fee ELSE 0
      END
    + (? * h.food_per_month)
    + CASE
        WHEN ? = 'semester' THEN h.transport_per_sem * 2
        WHEN ? = 'annual' THEN h.transport_per_sem * 2
        ELSE 0
      END
      AS total_fee
FROM fee_structure f, hostel_food_transport h
WHERE f.subject = ?;
"""

result = cursor.execute(
    query,
    (analytics, hostel, food_months, transport, transport, subject)
).fetchone()

print("\n----- Fee Breakdown -----")
print(f"Subject: {result[0]}")
print(f"Total Annual Cost: ₹{int(result[1])}")

----- Fee Breakdown -----
Subject: HR
Total Annual Cost: ₹252000

In [ ]:
#using oops concept

class CourseFee:

    #Class Variables
    SUBJECTS = ["HR", "Finance", "Marketing", "DS"]

    BASE_FEE = 200000
    ANALYTICS_EXTRA = 0.10
    HOSTEL_FEE = 200000
    FOOD_PER_MONTH = 2000
    TRANSPORT_PER_SEM = 13000

    def __init__(self):
        self.subject = ""
        self.analytics = ""
        self.hostel = ""
        self.food_months = 0
        self.transport = ""
        self.total_fee = 0

    def take_input(self):

        while True:
            subject = input("Enter subject (HR/Finance/Marketing/DS):").strip()
            if subject in self.SUBJECTS:
                self.subject = subject
                break
            print("Invalid subject.Choose from HR, Finance, Marketing, DS.")

        while True:
            analytics = input("Analytics? (Y/N):").strip().upper()
            if analytics in ["Y", "N"]:
                self.analytics = analytics
                break
            print("Enter Y or N only.")

        while True:
            hostel = input("Hostel? (Y/N):").strip().upper()
            if hostel in ["Y", "N"]:
                self.hostel = hostel
                break
            print("Enter Y or N only")

        while True:
            try:
                food_months = int(input("Food for how many months:"))
                if food_months >= 0:
                    self.food_months = food_months
                    break
                print("Months cannot be negative.")
            except ValueError:
                print("Please enter a valid number.")

        while True:
            transport = input("Transportation (semester/annual):").strip().lower()
            if transport in ["semester", "annual"]:
                self.transport = transport
                break
            print("Enter 'semester' or 'annual' only.")

    #Calculations
    def calculate_total_fee(self):

        self.total_fee = self.BASE_FEE

        if self.analytics == "Y" and self.subject != "DS":
            self.total_fee += self.BASE_FEE * self.ANALYTICS_EXTRA

        if self.hostel == "Y":
            self.total_fee += self.HOSTEL_FEE

        self.total_fee += self.food_months * self.FOOD_PER_MONTH

        #Annual means 2 semesters
        if self.transport == "annual":
            self.total_fee += self.TRANSPORT_PER_SEM * 2
        else:
            self.total_fee += self.TRANSPORT_PER_SEM

    def display_fee(self):
        print("\n----- Fee Breakdown ----")
        print(f"Subject: {self.subject}")
        print(f"Total Annual Cost in Rs: {int(self.total_fee)}")



if __name__ == "__main__":
    obj = CourseFee()
    obj.take_input()
    obj.calculate_total_fee()
    obj.display_fee()

14. Digitalize the book allotment process for school. Charges are mentioned here in the given table:

In [ ]:

#data
books_charges = {
    "Hindi": {"1-4": 60, "5-8": 100, "9-10": 150},
    "Marathi": {"1-4": 60, "5-8": 100, "9-10": 150},
    "English": {"1-4": 80, "5-8": 100, "9-10": 150},
    "Science": {"1-4": 90, "5-8": 120, "9-10": 200},
    "Maths": {"1-4": 100, "5-8": 140, "9-10": 250}
}

notebook_charges = {
    "square": {"100": 40, "200": 70},
    "4lines": {"100": 30, "200": 50},
    "2lines": {"100": 30, "200": 50},
    "single lines": {"100": 60, "200": 100},
    "a4 notebook": {"100": 100, "200": 180}
}

standard = int(input("Enter standard (1-10): "))

if 1 <= standard <= 4:
    std_group = "1-4"
elif 5 <= standard <= 8:
    std_group = "5-8"
elif 9 <= standard <= 10:
    std_group = "9-10"
else:
    print("Invalid standard")
    exit()

subjects = input(
    "Enter subjects (comma separated): "
).split(",")

notebook_type = input(
    "Enter notebook type (square / 4lines / 2lines / single lines / a4 notebook): "
).lower()

pages = input("Enter pages (100 / 200): ")

total_amount = 0

print("\n========== BOOK ALLOTMENT BILL ==========")
print(f"Standard : {standard}")
print("\nBooks:")

for subject in subjects:
    subject = subject.strip().title()
    if subject in books_charges:
        price = books_charges[subject][std_group]
        total_amount += price
        print(f"{subject:<10} : ₹{price}")
    else:
        print(f"{subject:<10} : Not Available")

print("\nNotebook:")

if notebook_type in notebook_charges and pages in notebook_charges[notebook_type]:
    nb_price = notebook_charges[notebook_type][pages]
    total_amount += nb_price
    print(f"{notebook_type.title()} ({pages} pages) : ₹{nb_price}")
else:
    print("Invalid notebook selection")

print("-----------------------------------------")
print(f"TOTAL AMOUNT : ₹{total_amount}")
print("-----------------------------------------")

15.

In [ ]:
from datetime import datetime

#input from user
start = input("Enter FD Start Date (dd-mm-yyyy): ")
end = input("Enter FD End Date (dd-mm-yyyy): ")

#convert to date objects
start_date = datetime.strptime(start, "%d-%m-%Y")
end_date = datetime.strptime(end, "%d-%m-%Y")

#calculate duration in days
days = (end_date - start_date).days
print("FD Duration:", days, "days")

#check bucket using simple if–else
if 7 <= days <= 45:
    rate = 5.75
elif 46 <= days <= 179:
    rate = 6.25
elif 180 <= days <= 210:
    rate = 6.35
elif 211 <= days < 365:
    rate = 6.40
elif 365 <= days < 730:
    rate = 6.80
elif 730 <= days < 1095:
    rate = 6.80
elif 1095 <= days < 1825:
    rate = 6.80
elif 1825 <= days <= 3650:
    rate = 6.85
else:
    rate = "Duration not supported"

print("Applicable Interest Rate:", rate, "%")

Enter FD Start Date (dd-mm-yyyy): 11-03-2003
Enter FD End Date (dd-mm-yyyy): 11-03-2026
FD Duration: 8401 days
Applicable Interest Rate: Duration not supported %

Typecasting

17

In [ ]:
a = 100

In [ ]:
a_str = str(a)
print(a_str, type(a_str))

100 <class 'str'>

In [ ]:
a_list = list(str(a))
print(a_list, type(a_list))

['1', '0', '0'] <class 'list'>

In [ ]:
a_tuple = tuple(str(a))
print(a_tuple, type(a_tuple))

('1', '0', '0') <class 'tuple'>

In [ ]:
a_dict = {a: "value"}
print(a_dict, type(a_dict))

{100: 'value'} <class 'dict'>

In [ ]:
a_set = set(str(a))
print(a_set, type(a_set))

{'1', '0'} <class 'set'>

In [ ]:
a_float = float(a)
print(a_float, type(a_float))

100.0 <class 'float'>

8.

In [ ]:
city = "Pune"

In [ ]:
float(city)

In [ ]:
list(city)

['P', 'u', 'n', 'e']

In [ ]:
tuple(city)

('P', 'u', 'n', 'e')

In [ ]:
set(city)

9.

In [ ]:
int(marks)

In [ ]:
float(marks)

In [ ]:
list(marks)

In [ ]:
tuple(marks)

In [ ]:
dict(marks)

In [ ]:
set(marks)

List operations

10

In [ ]:
snames = []
print(snames)

[]

In [ ]:
snames.append(20)
print(snames)

[20]

In [ ]:
snames.extend([30])
print(snames)

[20, 30]

In [ ]:
snames.append([40, 50])
print(snames)

[20, 30, [40, 50]]

In [ ]:
snames.extend(["WORK"])
print(snames)

[20, 30, [40, 50], 'WORK']

In [ ]:
combo = [1, 'a', 'b', 2, 3]
print(combo)

[1, 'a', 'b', 2, 3]

In [ ]:
result1 = combo + snames
print(result1)

[1, 'a', 'b', 2, 3, 20, 30, [40, 50], 'WORK']

In [ ]:
snames.append(combo)
print(snames)

[20, 30, [40, 50], 'WORK', [1, 'a', 'b', 2, 3]]

In [ ]:
snames.extend(combo)
print(snames)

[20, 30, [40, 50], 'WORK', [1, 'a', 'b', 2, 3], 1, 'a', 'b', 2, 3]

11.

In [ ]:
l1 = [10, 20]
l3 = [1, 2, 3, 4, 5, 6, 7]

l3.insert(3, l1)
print(l3)

[1, 2, 3, [10, 20], 4, 5, 6, 7]

12.

In [ ]:
collection = [1, 2, 3, ['a', 'b', 'c'], 100, 'Nisha', 20.50, 90.10]
for i in range(len(collection)):
    if type(collection[i]) == int or type(collection[i]) == float:
        collection[i] = collection[i] * 5

print(collection)

[5, 10, 15, ['a', 'b', 'c'], 500, 'Nisha', 102.5, 450.5]

In [ ]:
collection.remove('Nisha')
print(collection)

[5, 10, 15, ['a', 'b', 'c'], 500, 102.5, 450.5]

In [ ]:
index_value = collection.index(102.5)
print(index_value)

5

13.

In [ ]:
squares = [x*x for x in range(1, 11)]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

14

In [ ]:
div_by_13 = [x for x in range(1, 201) if x % 13 == 0]
print(div_by_13)

[13, 26, 39, 52, 65, 78, 91, 104, 117, 130, 143, 156, 169, 182, 195]

15.

In [ ]:
div_by_4 = [x for x in range(300, 401) if x % 4 == 0]
print(div_by_4)

[300, 304, 308, 312, 316, 320, 324, 328, 332, 336, 340, 344, 348, 352, 356, 360, 364, 368, 372, 376, 380, 384, 388, 392, 396, 400]

16

In [ ]:
x = 3
y = 2
x_list = [i for i in range(x)]
y_list = [j for j in range(y)]

combo = [[i, j] for i in x_list for j in y_list]

print("x_list =", x_list)
print("y_list =", y_list)
print("Output =", combo)

x_list = [0, 1, 2]
y_list = [0, 1]
Output = [[0, 0], [0, 1], [1, 0], [1, 1], [2, 0], [2, 1]]

17-21 are theory questions

22.

In [ ]:
s1 = {1, 2, 3, 4, 5}
s2 = {4, 5, 6, 7}
print(s1.union(s2))
print(s1.intersection(s2))
print(s1.difference(s2))
print(s2.difference(s1))
print(s1.symmetric_difference(s2))

{1, 2, 3, 4, 5, 6, 7}
{4, 5}
{1, 2, 3}
{6, 7}
{1, 2, 3, 6, 7}

23

In [ ]:
s1 = {1, 2, 3, 4, 5}
l2 = [4, 5, 6, 7]

In [ ]:
s1 = {1, 2, 3, 4, 5}
s2 = {4, 5, 6, 7}

In [ ]:
print(s1.union(s2))
print(s1.intersection(s2))
print(s1.difference(s2))
print(s1.symmetric_difference(s2))

{1, 2, 3, 4, 5, 6, 7}
{4, 5}
{1, 2, 3}
{1, 2, 3, 6, 7}

24.

In [ ]:
name = input("Enter your name: ")
dob = input("Enter your DOB (dd-mm-yyyy): ")
first_part = name[:4].upper()
day, month, year = dob.split("-")
password = first_part + "@" + day + month
print("Generated Password:", password)

Enter your name: SURESH
Enter your DOB (dd-mm-yyyy): 05-05-1978
Generated Password: SURE@0505

25

In [ ]:
name = input("Enter your name: ")
dob = input("Enter your DOB (dd-mm-yyyy): ")
first_part = name[:4].upper()
day, month, year = dob.split("-")
password = first_part + "@" + year
print("Generated Password:", password)

Enter your name: SURESH
Enter your DOB (dd-mm-yyyy): 05-05-1978
Generated Password: SURE@1978

26

In [ ]:
for i in range(1, 5):
    print("* " * i)

*
* *
* * *
* * * *

27

In [ ]:
for i in range(4, 0, -1):
    print("*" * i)

****
***
**
*

28

In [ ]:
str_val = "ABCD"
for i in range(1, len(str_val) + 1):
    print(" ".join(str_val[:i]))

A
A B
A B C
A B C D

29

In [ ]:
str_val = "ABCD"
for i in range(len(str_val)):
    print(str_val[i] * (i + 1))

A
BB
CCC
DDDD

30

In [ ]:
for i in range(1, 5):
    print(str(i) * i)

1
22
333
4444

31

In [ ]:
val = "ABCD"
rev = val[::-1]
for i in range(1, len(rev) + 1):
    print(rev[:i])

D
DC
DCB
DCBA

32

In [ ]:
s = input("Enter a string: ")
rev = s[::-1]
for i in range(1, len(rev) + 1):
    print(rev[:i])

Enter a string: sakshi
i
ih
ihs
ihsk
ihska
ihskas

33

In [ ]:
odd_numbers = []
for i in range(1, 11):
    if i % 2 != 0:
        odd_numbers.append(i)

print(odd_numbers)

[1, 3, 5, 7, 9]

In [ ]:
odd_numbers = [i for i in range(1, 11) if i % 2 != 0]
print(odd_numbers)

[1, 3, 5, 7, 9]

34

In [ ]:
even_numbers = []
for i in range(200, 251):
    if i % 2 == 0:
        even_numbers.append(i)

print(even_numbers)

[200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250]

35

In [ ]:
List2 = [2, 70, 'work', "para", 2.5, [1,2,3], (1,2), {1,2}, {1:'a', 2:'b'}, 3, 10, 302.5]
result = []
for item in List2:
    try:
        result.append(item * 2)
    except TypeError:
        result.append(f"Cannot multiply: {item}")
print(result)

[4, 140, 'workwork', 'parapara', 5.0, [1, 2, 3, 1, 2, 3], (1, 2, 1, 2), 'Cannot multiply: {1, 2}', "Cannot multiply: {1: 'a', 2: 'b'}", 6, 20, 605.0]

36

In [ ]:
List2 = [2, 70, 'work', "para", 2.5, [1,2,3], (1,2), {1,2}, {1:'a', 2:'b'}, 3, 10, 302.5]
list3 = []
for item in List2:
    try:
        list3.append(item * 2)
    except TypeError:
        list3.append(f"Cannot multiply: {item}")
print(list3)

[4, 140, 'workwork', 'parapara', 5.0, [1, 2, 3, 1, 2, 3], (1, 2, 1, 2), 'Cannot multiply: {1, 2}', "Cannot multiply: {1: 'a', 2: 'b'}", 6, 20, 605.0]

37

In [ ]:
def accept_marks():
    while True:
        try:
            marks = float(input("Enter marks (0–100): "))
            if marks < 0 or marks > 100:
                raise ValueError("Marks must be between 0 and 100")
        except ValueError as e:
            print("Invalid input:", e)
            print("Please enter valid marks.\n")
        else:
            print("Marks accepted:", marks)
            return marks
accept_marks()

Enter marks (0–100): 67
Marks accepted: 67.0

67.0

38

In [ ]:
def validate_name(name):
    try:
        if not name.isalpha():
            raise ValueError("Name must contain only alphabets with no spaces, digits, or special characters.")
        print("Valid name:", name)
        return True
    except ValueError as e:
        print("Invalid name:", e)
        return False
fname = input("Enter first name: ")
validate_name(fname)
lname = input("Enter last name: ")
validate_name(lname)

Enter first name: sakhsi
Valid name: sakhsi
Enter last name: aisoija
Valid name: aisoija

True

39

In [ ]:
def validate_mobile(mobile):
    try:
        if len(mobile) != 10:
            raise ValueError("Mobile number must be exactly 10 digits.")
        if not mobile.isdigit():
            raise ValueError("Mobile number must contain only numbers (0–9).")
        print("Valid Mobile Number:", mobile)
        return True
    except ValueError as e:
        print("Invalid Mobile Number:", e)
        return False
mob = input("Enter mobile number: ")
validate_mobile(mob)

Enter mobile number: 9860456787
Valid Mobile Number: 9860456787

True

40

In [ ]:
def generate_password():
    name = input("Enter your name: ")
    dob = input("Enter your DOB (dd-mm-yyyy): ")
    first4 = name[:4]
    try:
        year = dob.split("-")[2]
    except:
        print("Invalid DOB format. Use dd-mm-yyyy")
        return
    password = first4 + "@" + year
    print("Generated Password:", password)
generate_password()

Enter your name: saksih
Enter your DOB (dd-mm-yyyy): 11-2-2003
Generated Password: saks@2003

41

In [ ]:
data={}
cust_no=1
while True:
    name=input("Enter name: ")
    dob=input("Enter DOB: ")
    mobile=input("Enter mobile: ")
    data[cust_no]={"name":name,"DOB":dob,"mobile":mobile}
    print(data)
    cust_no+=1
    ch=input("Do you want to add more? (y/n): ")
    if ch.lower()!="y":
        break

Enter name: joe
Enter DOB: 11-02-2003
Enter mobile: 9860456787
{1: {'name': 'joe', 'DOB': '11-02-2003', 'mobile': '9860456787'}}
Do you want to add more? (y/n): n

42

In [ ]:
data={}
cust_no=1
while True:
    name=input("Enter name: ")
    dob=input("Enter DOB: ")
    mobile=input("Enter mobile: ")
    data[cust_no]={"name":name,"DOB":dob,"mobile":mobile}
    with open("cust_info.txt","a") as f:
        f.write(str({cust_no:data[cust_no]})+"\n")
    print(data)
    cust_no+=1
    ch=input("Do you want to add more? (y/n): ")
    if ch.lower()!="y":
        break

Enter name: sak
Enter DOB: 11-0-90
Enter mobile: 75745777475
{1: {'name': 'sak', 'DOB': '11-0-90', 'mobile': '75745777475'}}
Do you want to add more? (y/n): n

43

In [ ]:
import ast
data={}
try:
    with open("cust_info.txt","r") as f:
        for line in f:
            entry=ast.literal_eval(line.strip())
            data.update(entry)
except FileNotFoundError:
    pass
cust_no=max(data.keys(),default=0)+1
while True:
    name=input("Enter name: ")
    dob=input("Enter DOB: ")
    mobile=input("Enter mobile: ")
    data[cust_no]={"name":name,"DOB":dob,"mobile":mobile}
    with open("cust_info.txt","a") as f:
        f.write(str({cust_no:data[cust_no]})+"\n")
    print(data)
    cust_no+=1
    ch=input("Do you want to add more? (y/n): ")
    if ch.lower()!="y":
        break

Enter name: sakshi
Enter DOB: 11-03-2003
Enter mobile: 9860456787
{1: {'name': 'sakshi', 'DOB': '11-03-2003', 'mobile': '9860456787'}}
Do you want to add more? (y/n): n

44.

In [ ]:
import sqlite3

conn = sqlite3.connect("customer.db")
cursor = conn.cursor()
cursor.execute('''CREATE TABLE IF NOT EXISTS cust_info (
    sr_no INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    DOB TEXT NOT NULL,
    mobile TEXT NOT NULL
)''')

def validate_name(name):
    return name.isalpha()

def validate_DOB(dob):
    parts=dob.split("-")
    return len(parts)==3 and all(part.isdigit() for part in parts)

def validate_mobile(mobile):
    return mobile.isdigit() and len(mobile)==10

while True:
    name=input("Enter name: ")
    if not validate_name(name):
        print("Invalid name")
        continue
    dob=input("Enter DOB (dd-mm-yyyy): ")
    if not validate_DOB(dob):
        print("Invalid DOB")
        continue
    mobile=input("Enter mobile: ")
    if not validate_mobile(mobile):
        print("Invalid mobile")
        continue
    cursor.execute("INSERT INTO cust_info(name,DOB,mobile) VALUES(?,?,?)",(name,dob,mobile))
    conn.commit()
    print("Record inserted successfully")
    ch=input("Do you want to add more? (y/n): ")
    if ch.lower()!="y":
        break

conn.close()

Enter name: sakshi
Enter DOB (dd-mm-yyyy): 11-03-2003
Enter mobile: 9860456787
Record inserted successfully
Do you want to add more? (y/n): n

45

In [ ]:
Dict1 = {"Key":{"subkey":20}, "k2":{"sub2":5}, "k3":{"sub4":16}, "k4":{"sub4":6}}
sorted_dict = dict(sorted(Dict1.items(), key=lambda x: list(x[1].values())[0]))
print(sorted_dict)

{'k2': {'sub2': 5}, 'k4': {'sub4': 6}, 'k3': {'sub4': 16}, 'Key': {'subkey': 20}}

46

In [ ]:
from datetime import datetime
def calculate_age(dob):
    birth_date = datetime.strptime(dob, "%d-%m-%Y")
    today = datetime.today()
    age = today.year - birth_date.year - ((today.month, today.day) < (birth_date.month, birth_date.day))
    return age
dob_input = input("Enter DOB (dd-mm-yyyy): ")
print("Age:", calculate_age(dob_input))

47

In [ ]:
from datetime import datetime
def check_age_eligibility(dob, eligibility_age):
    birth_date = datetime.strptime(dob, "%d-%m-%Y")
    today = datetime.today()
    age = today.year - birth_date.year - ((today.month, today.day) < (birth_date.month, birth_date.day))
    if age >= eligibility_age:
        return True, age
    else:
        return False, age
dob_input = input("Enter DOB (dd-mm-yyyy): ")
eligibility = int(input("Enter eligibility age: "))
eligible, age = check_age_eligibility(dob_input, eligibility)
if eligible:
    print(f"Customer is eligible. Age: {age}")
else:
    print(f"Customer is not eligible. Age: {age}")

48

In [ ]:
def is_palindrome(s):
    s_clean = s.upper()
    if s_clean == s_clean[::-1]:
        return True
    else:
        return False
user_input = input("Enter a string: ")
if is_palindrome(user_input):
    print(f"{user_input} is a palindrome")
else:
    print(f"{user_input} is not a palindrome")

49

In [ ]:
def fibonacci_upto_100():
    fib_series = [0, 1]
    while fib_series[-1] + fib_series[-2] <= 100:
        fib_series.append(fib_series[-1] + fib_series[-2])
    return fib_series
print(fibonacci_upto_100())

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

50

In [ ]:
def factorial(n):
    if n < 0:
        return "Factorial not defined for negative numbers"
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result
num = int(input("Enter a number: "))
print(f"Factorial of {num} is {factorial(num)}")

Enter a number: 455
Factorial of 455 is 330652177144116372595018778066441848536765021855923937116013806354820133339911166774726909168510073646273149461962714720323801914114452998605141527590886835057103132498721841125372484516782310305886786036506845195181388234028257178854518790119548768972158342163204004863590180783935484742777796047161291172213569193388737871282337456018280474418816084928896428207187937949372400830704309158727989729198932089443651497843963584331385104607844641147204400652724774895706116336924137717336375333537937839596917646683058840802459122198080528501214816228432895875152786115889662540609344137191713438257078317944879918620289499096298571401173081643113550142905160312219102635120026451677859933619652611489930147908449449212745152723039968780454460747096676649134863495097580145578650645087521884858404539459004627725819048970247360794586905516268714382855816126651954852845064331936741905508613974215580712960000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

51

In [ ]:
numbers = [10, 45, 67, 23, 89, 12]
largest = max(numbers)
print("Largest number is:", largest)
largest2 = numbers[0]
for num in numbers:
    if num > largest2:
        largest2 = num
print("Largest number using loop is:", largest2)

Largest number is: 89
Largest number using loop is: 89

52

In [ ]:
lst = [1, 2, 2, 3, 1, 4, 2, 3]
freq = {}
for item in lst:
    if item in freq:
        freq[item] += 1
    else:
        freq[item] = 1
print("Frequency of each element:", freq)
from collections import Counter
freq2 = Counter(lst)
print("Frequency using Counter:", freq2)

Frequency of each element: {1: 2, 2: 3, 3: 2, 4: 1}
Frequency using Counter: Counter({2: 3, 1: 2, 3: 2, 4: 1})

53

In [ ]:
l1 = [1, 2, 3, 4, 5]
l2 = [3, 2, 8, 7, 9]
common = [i for i in l1 if i in l2]
print("Common elements:", common)
common_set = list(set(l1) & set(l2))
print("Common elements using set:", common_set)

Common elements: [2, 3]
Common elements using set: [2, 3]

54

In [ ]:
import sqlite3
from datetime import datetime

conn = sqlite3.connect("shopdb.db")
cursor = conn.cursor()

cursor.execute("CREATE TABLE IF NOT EXISTS user(uid INTEGER PRIMARY KEY AUTOINCREMENT, mobile TEXT, passkey TEXT, date TEXT)")
cursor.execute("CREATE TABLE IF NOT EXISTS product(pid INTEGER PRIMARY KEY AUTOINCREMENT, pname TEXT)")
cursor.execute("CREATE TABLE IF NOT EXISTS orders(oid INTEGER PRIMARY KEY AUTOINCREMENT, uid INTEGER, pid INTEGER, FOREIGN KEY(uid) REFERENCES user(uid), FOREIGN KEY(pid) REFERENCES product(pid))")

class User:
    def __init__(self,mobile,passkey):
        self.mobile = mobile
        self.passkey = passkey
    def signup(self):
        date = datetime.today().strftime("%Y-%m-%d")
        cursor.execute("INSERT INTO user(mobile,passkey,date) VALUES(?,?,?)",(self.mobile,self.passkey,date))
        conn.commit()
        print("Signup successful")
    def signin(self):
        cursor.execute("SELECT * FROM user WHERE mobile=? AND passkey=?",(self.mobile,self.passkey))
        if cursor.fetchone():
            print("Sign in successful")
            return True
        else:
            print("Invalid credentials")
            return False
    def view_products(self):
        cursor.execute("SELECT * FROM product")
        print(cursor.fetchall())
    def view_orders(self):
        cursor.execute("SELECT o.oid,u.mobile,p.pname FROM orders o JOIN user u ON o.uid=u.uid JOIN product p ON o.pid=p.pid WHERE u.mobile=?",(self.mobile,))
        print(cursor.fetchall())
    def place_order(self,pid):
        cursor.execute("SELECT uid FROM user WHERE mobile=?",(self.mobile,))
        uid = cursor.fetchone()[0]
        cursor.execute("INSERT INTO orders(uid,pid) VALUES(?,?)",(uid,pid))
        conn.commit()
        print("Order placed")

class Product:
    def __init__(self,pname):
        self.pname = pname
    def add_product(self):
        cursor.execute("INSERT INTO product(pname) VALUES(?)",(self.pname,))
        conn.commit()
        print("Product added")

p1 = Product("Laptop")
p1.add_product()
p2 = Product("Mouse")
p2.add_product()

u1 = User("1234567890","pass123")
u1.signup()
u1.signin()
u1.view_products()
u1.place_order(1)
u1.view_orders()

55- not mentioned

56

In [ ]:
def generate_bill(items):
    print("---------- BILL ----------")
    print("{:<5} {:<15} {:<10} {:<10}".format("S.No","Item","Qty","Price"))
    print("-"*45)
    total_amount = 0
    for i, (name, qty, price) in enumerate(items, start=1):
        amount = qty * price
        total_amount += amount
        print("{:<5} {:<15} {:<10} {:<10}".format(i, name, qty, amount))
    print("-"*45)
    print("{:<5} {:<15} {:<10} {:<10}".format("","TOTAL","",""+str(total_amount)))
    print("--------------------------")

# Example usage
items = [("Apple", 3, 50), ("Banana", 5, 10), ("Milk", 2, 40)]
generate_bill(items)

---------- BILL ----------
S.No  Item            Qty        Price
---------------------------------------------
1     Apple           3          150
2     Banana          5          50
3     Milk            2          80
---------------------------------------------
      TOTAL                      280
--------------------------

 to - submit restaurent bill printing

In [ ]:
hotel_name = "Welcome to Sakshi's Eatery"

#Menu
menu = {
    1: ("idli", 30),
    2: ("dosa", 50),
    3: ("poha", 25),
    4: ("upma", 20)
}

#Show menu
print("--------- MENU ---------")
for sr, (item, price) in menu.items():
    print(f"{sr}. {item} - ₹{price}")
print("------------------------")

#User selects item
choice = None
while choice is None:
    try:
        choice_input = input("Enter the sr number of the item you want: ")
        choice = int(choice_input)
        if choice not in menu:
            print("Invalid serial number. Please choose from the menu.")
            choice = None
    except ValueError:
        print("Invalid input. Please enter a number corresponding to the item.")
        choice = None

quantity = None
while quantity is None:
    try:
        quantity_input = input("Enter quantity: ")
        quantity = int(quantity_input)
        if quantity <= 0:
            print("Quantity must be a positive number.")
            quantity = None
    except ValueError:
        print("Invalid quantity. Please enter a number.")
        quantity = None


#Get item and price
item_name, item_price = menu[choice]

#items list for bill
items = [(choice, item_name, quantity, item_price)]

total = sum(qty * price for _, _, qty, price in items)

print("=" * 50)
print(f"|{hotel_name.center(48)}|")
print("=" * 50)
print(f"| {'sr':<3} {'Menu':<15} {'qunt':<8} {'price':>17} |")
print("-" * 50)

for sr, menu_item, qty, price in items:
    print(f"| {sr:<3} {menu_item:<15} {qty:<8} {price:>17} |")

print("-" * 50)
print(f"| {'Total':<30} {total:>15} |")
print("=" * 50)

--------- MENU ---------
1. idli - ₹30
2. dosa - ₹50
3. poha - ₹25
4. upma - ₹20
------------------------
Enter the sr number of the item you want: 1
Enter quantity: 3
==================================================
|           Welcome to Sakshi's Eatery           |
==================================================
| sr  Menu            qunt                 price |
--------------------------------------------------
| 1   idli            3                       30 |
--------------------------------------------------
| Total                                       90 |
==================================================

sql-lite

In [ ]:
import sqlite3

#Create database
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

#Create menu table
cursor.execute("""
CREATE TABLE menu(
    sr INTEGER PRIMARY KEY,
    item TEXT,
    price INTEGER
);
""")

#Inserting menu items
cursor.executemany("""
INSERT INTO menu VALUES (?, ?, ?);
""", [
    (1, "idli", 30),
    (2, "dosa", 50),
    (3, "poha", 25),
    (4, "upma", 20)
])

conn.commit()

In [ ]:
print("--------- MENU ---------")
result = cursor.execute("SELECT * FROM menu").fetchall()

for row in result:
    print(f"{row[0]}. {row[1]} - ₹{row[2]}")
print("------------------------")

--------- MENU ---------
1. idli - ₹30
2. dosa - ₹50
3. poha - ₹25
4. upma - ₹20
------------------------

In [ ]:

while True:
    try:
        choice = int(input("Enter the sr number of the item you want: "))
        row = cursor.execute("SELECT * FROM menu WHERE sr=?", (choice,)).fetchone()
        if row:
            break
        else:
            print("Invalid serial number. Choose from the menu.")
    except ValueError:
        print("Invalid input. Enter a number.")

while True:
    try:
        quantity = int(input("Enter quantity: "))
        if quantity > 0:
            break
        else:
            print("Quantity should be a positive number.")
    except ValueError:
        print("Invalid quantity. Enter a number.")

Enter the sr number of the item you want: 1
Enter quantity: 1

In [ ]:
query = """
SELECT
    m.sr,
    m.item,
    ? AS quantity,
    m.price,
    (m.price * ?) AS total_price
FROM menu m
WHERE m.sr = ?;
"""

bill_item = cursor.execute(query, (quantity, quantity, choice)).fetchone()

In [ ]:
hotel_name = "Welcome to Sakshi's Eatery"
sr, item_name, qty, price, total = bill_item

print("=" * 50)
print(f"|{hotel_name.center(48)}|")
print("=" * 50)
print(f"| {'sr':<3} {'Menu':<15} {'qunt':<8} {'price':>17} |")
print("-" * 50)

print(f"| {sr:<3} {item_name:<15} {qty:<8} {price:>17} |")

print("-" * 50)
print(f"| {'Total':<30} {total:>15} |")
print("=" * 50)

==================================================
|           Welcome to Sakshi's Eatery           |
==================================================
| sr  Menu            qunt                 price |
--------------------------------------------------
| 1   idli            1                       30 |
--------------------------------------------------
| Total                                       30 |
==================================================

In [ ]:
#using oops concept

class MenuItem:
    def __init__(self, sr, name, price):
        self.sr = sr
        self.name = name
        self.price = price


class Menu:
    def __init__(self):
        self.items = {
            1: MenuItem(1, "idli", 30),
            2: MenuItem(2, "dosa", 50),
            3: MenuItem(3, "poha", 25),
            4: MenuItem(4, "upma", 20)
        }

    def display_menu(self):
        print("--------- MENU ---------")
        for item in self.items.values():
            print(f"{item.sr}. {item.name} - ₹{item.price}")
        print("------------------------")

    def get_item(self, sr):
        return self.items.get(sr, None)


class Order:
    def __init__(self):
        self.selected_items = []

    def add_item(self, item, quantity):
        self.selected_items.append((item, quantity))

    def calculate_total(self):
        return sum(item.price * qty for item, qty in self.selected_items)


class BillPrinter:
    def __init__(self, hotel_name):
        self.hotel_name = hotel_name

    def print_bill(self, order):
        print("=" * 50)
        print(f"|{self.hotel_name.center(48)}|")
        print("=" * 50)
        print(f"| {'sr':<3} {'Menu':<15} {'qunt':<8} {'price':>17} |")
        print("-" * 50)

        for item, qty in order.selected_items:
            print(f"| {item.sr:<3} {item.name:<15} {qty:<8} {item.price:>17} |")

        print("-" * 50)
        total = order.calculate_total()
        print(f"| {'Total':<30} {total:>15} |")
        print("=" * 50)

hotel_name = "Welcome to Sakshi's Eatery"
menu = Menu()
order = Order()
bill = BillPrinter(hotel_name)

menu.display_menu()

#Select item
while True:
    try:
        choice = int(input("Enter the sr number of the item you want: "))
        selected_item = menu.get_item(choice)
        if selected_item:
            break
        else:
            print("Invalid serial number. Try again.")
    except ValueError:
        print("Enter a valid number.")

#Quantity
while True:
    try:
        quantity = int(input("Enter quantity: "))
        if quantity > 0:
            break
        else:
            print("Quantity must be positive.")
    except ValueError:
        print("Enter a valid number.")

#Add to order
order.add_item(selected_item, quantity)

bill.print_bill(order)

--------- MENU ---------
1. idli - ₹30
2. dosa - ₹50
3. poha - ₹25
4. upma - ₹20
------------------------
Enter the sr number of the item you want: 1
Enter quantity: 1
==================================================
|           Welcome to Sakshi's Eatery           |
==================================================
| sr  Menu            qunt                 price |
--------------------------------------------------
| 1   idli            1                       30 |
--------------------------------------------------
| Total                                       30 |
==================================================

bill generate

In [ ]:
restaurant = {}

menu = {
    1: ("Pizza", 200),
    2: ("Burger", 120),
    3: ("Coke", 40),
    4: ("Pasta", 150),
    5: ("Coffee", 80),
}

def take_order():
    table_no = input("Enter table number: ")

    print("\n--- MENU ---")
    for num, (item, price) in menu.items():
        print(f"{num}. {item} - ₹{price}")

    print("\nSelect items (comma separated numbers or names):")
    choices = input("Your order: ").split(",")

    items = []          #list of item names
    quantities = []     #list of quantities

    for user_choice in choices:
        choice = user_choice.strip().lower()


        if choice.isdigit() and int(choice) in menu:
            item_name = menu[int(choice)][0]
        else:

            item_name = None
            for num, (name, _) in menu.items():
                if choice == name.lower():
                    item_name = name
                    break

        if item_name is None:
            print(f"Invalid menu option: {user_choice}")
            continue

        qty = input(f"Enter quantity for {item_name}: ")
        if qty.isdigit():
            qty = int(qty)
        else:
            print("Invalid quantity. Setting quantity = 1")
            qty = 1

        items.append(item_name)
        quantities.append(qty)

    restaurant[table_no] = {
        "order": items,
        "quantities": quantities,
        "delivered": False,
        "bill": 0
    }

    print(f"\nOrder stored for Table {table_no}: {items}\n")
    return table_no

def deliver_order(table_no):
    restaurant[table_no]["delivered"] = True
    print(f"Order delivered to Table {table_no}\n")

def generate_bill(table_no):
    items = restaurant[table_no]["order"]
    quantities = restaurant[table_no]["quantities"]

    total = 0

    for index, item in enumerate(items):
        qty = quantities[index]

        for name, price in menu.values():
            if item == name:
                total += price * qty

    restaurant[table_no]["bill"] = total
    print(f"Bill generated for Table {table_no}\n")

def print_bill(table_no):
    print("\n------ BILL ------")
    print(f"Table Number: {table_no}")
    print("Items Ordered:")

    items = restaurant[table_no]["order"]
    quantities = restaurant[table_no]["quantities"]

    for i in range(len(items)):
        print(f"{items[i]} x {quantities[i]}")

    print("Delivered:", restaurant[table_no]["delivered"])
    print("Total Bill: ₹", restaurant[table_no]["bill"])
    print("------------------\n")

table = take_order()
deliver_order(table)
generate_bill(table)
print_bill(table)

Enter table number: 2

--- MENU ---
1. Pizza - ₹200
2. Burger - ₹120
3. Coke - ₹40
4. Pasta - ₹150
5. Coffee - ₹80

Select items (comma separated numbers or names):
Your order: Pizza
Enter quantity for Pizza: 3

Order stored for Table 2: ['Pizza']

Order delivered to Table 2

Bill generated for Table 2


------ BILL ------
Table Number: 2
Items Ordered:
Pizza x 3
Delivered: True
Total Bill: ₹ 600
------------------

erp diagram code

In [ ]:
def create_user():
    print("\n--- Create User Account ---")
    name = input("Enter your name: ")
    email = input("Enter your email: ")
    password = input("Enter your password: ")
    print("\nAccount created successfully!\n")
    return {"name": name, "email": email, "password": password}


products_data = {
    "Cleansers": {
        "Cetaphil": {"Gentle Cleanser": 350, "Oily Skin Cleanser": 450},
        "La Roche-Posay": {"Toleriane Cleanser": 900, "Effaclar Gel": 1200}
    },

    "Moisturizers": {
        "Neutrogena": {"Hydro Boost Gel": 800, "Oil-Free Moisturizer": 500},
        "CeraVe": {"Moisturizing Cream": 850, "Lotion": 700}
    },

    "Sunscreens": {
        "Aqualogica": {"Glow Sunscreen SPF 50": 399, "Radiance+ Dewy SPF 50": 499},
        "Dermaco": {"Matte Sunscreen SPF 50": 299, "Ultra Matte SPF 60": 399}
    }
}


def choose_category():
    print("\n--- Categories ---")
    categories = list(products_data.keys())

    for i, cat in enumerate(categories, 1):
        print(f"{i}. {cat}")

    choice = int(input("Choose a category: "))
    return categories[choice - 1]


def choose_brand(category):
    print(f"\n--- Brands in {category} ---")
    brands = list(products_data[category].keys())

    for i, brand in enumerate(brands, 1):
        print(f"{i}. {brand}")

    choice = int(input("Choose a brand: "))
    return brands[choice - 1]


def choose_product(category, brand):
    print(f"\n--- Products from {brand} ---")
    items = products_data[category][brand]

    product_names = list(items.keys())

    for i, prod in enumerate(product_names, 1):
        print(f"{i}. {prod} - ₹{items[prod]}")

    choice = int(input("Choose a product: "))
    selected_product = product_names[choice - 1]
    price = items[selected_product]

    return selected_product, price


def add_to_cart(cart, product, price):
    qty = int(input(f"Enter quantity for {product}: "))
    cart.append({"product": product, "price": price, "qty": qty})
    print("Added to cart!\n")


def generate_bill(cart):
    print("\n----- BILL SUMMARY -----")
    total = 0

    for item in cart:
        amount = item["price"] * item["qty"]
        total += amount
        print(f"{item['product']} (x{item['qty']}) - ₹{amount}")

    print("-------------------------")
    print(f"TOTAL AMOUNT: ₹{total}")
    return total


    print("\n--- Payment Options ---")
    print("1. UPI")
    print("2. Debit Card")
    print("3. Cash on Delivery")

    choice = int(input("Choose payment method: "))
    if choice == 1:
        input("Enter UPI ID: ")
    elif choice == 2:
        input("Enter Card Number: ")
        input("Enter CVV: ")
    else:
        print("Pay on delivery.")

    print("\nPayment Successful! Order Confirmed.\n")


def review():
    print("\n--- Rate Your Shopping Experience ---")
    rating = int(input("Rate us (1–5): "))
    feedback = input("Write a short review: ")
    print("\nThank you for your feedback!\n")

def main():
    user = create_user()
    cart = []

    print("--- Welcome to SkinGlow Shopping ---")

    while True:
        print("\n1. Start Shopping\n2. Exit")
        main_choice = int(input("Enter choice: "))

        if main_choice == 2:
            print("Thank you for visiting!")
            break

        category = choose_category()
        brand = choose_brand(category)
        product, price = choose_product(category, brand)
        add_to_cart(cart, product, price)

        more = input("Do you want to continue shopping? (yes/no): ").lower()
        if more != "yes":
            total = generate_bill(cart)
            payment(total)
            review()
            break


main()

--- Create User Account ---

Account created successfully!

--- Welcome to SkinGlow Shopping ---

1. Start Shopping
2. Exit

Database connection

In [ ]:
!pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.3.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
Downloading pyodbc-5.3.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (340 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 340.3/340.3 kB 7.0 MB/s eta 0:00:00
Installing collected packages: pyodbc
Successfully installed pyodbc-5.3.0

In [ ]:
!pip install mysql-connector

Collecting mysql-connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 78.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: mysql-connector
  Building wheel for mysql-connector (setup.py) ... done
  Created wheel for mysql-connector: filename=mysql_connector-2.2.9-cp312-cp312-linux_x86_64.whl size=247950 sha256=95c56333197ea6e73525909db6eafb1e1efcfc0a9d1312dea913c1368d0c64ac
  Stored in directory: /root/.cache/pip/wheels/03/17/fa/d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql-connector
Installing collected packages: mysql-connector
Successfully installed mysql-connector-2.2.9

In [ ]:
!pip install MySQL-connector-python

Collecting MySQL-connector-python
  Downloading mysql_connector_python-9.6.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.6.0-cp312-cp312-manylinux_2_28_x86_64.whl (34.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.5/34.5 MB 33.7 MB/s eta 0:00:00
Installing collected packages: MySQL-connector-python
Successfully installed MySQL-connector-python-9.6.0

In [ ]:
import mysql.connector as mysqlcon

In [ ]:
import sqlite3

# Create a database file
conn = sqlite3.connect("mydatabase.db")

cursor = conn.cursor()

print("Connected to SQLite!")

Connected to SQLite!

In [ ]:
cursor.execute("DROP TABLE IF EXISTS users")

cursor.execute("""
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    stud_age INTEGER
)
""")

conn.commit()

In [ ]:
cursor.execute("INSERT INTO users (id, name, stud_age) VALUES (?, ?, ?)", (1, "aaditya", 25))
cursor.execute("INSERT INTO users (id, name, stud_age) VALUES (?, ?, ?)", (2, "malhar", 30))
cursor.execute("INSERT INTO users (id, name, stud_age) VALUES (?, ?, ?)", (3, "Sakshi", 30))

conn.commit()

In [ ]:
cursor.execute("SELECT * FROM users")
rows = cursor.fetchall()

for row in rows:
    print(row)

(1, 'aaditya', 25)
(2, 'malhar', 30)
(3, 'Sakshi', 30)

In [ ]:
import pandas as pd

df = pd.read_sql_query("SELECT * FROM users", conn)
df

   id     name  stud_age
0   1  aaditya        25
1   2   malhar        30
2   3   Sakshi        30

hotel management code- SQL

In [ ]:
import sqlite3
conn = sqlite3.connect("mydatabase.db")

cursor = conn.cursor()

print("Connected to SQLite!")

Connected to SQLite!

In [ ]:
cursor.execute("DROP TABLE IF EXISTS menu")
conn.commit()

cursor.execute("""
CREATE TABLE IF NOT EXISTS menu (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    menu_name TEXT,
    price INTEGER
)
""")
conn.commit()

cursor.execute("INSERT INTO menu (id, menu_name, price) VALUES (?, ?, ?)", (1, "Burger", 25))
cursor.execute("INSERT INTO menu (id, menu_name, price) VALUES (?, ?, ?)", (2, "Pizza", 30))
cursor.execute("INSERT INTO menu (id, menu_name, price) VALUES (?, ?, ?)", (3, "Chai", 30))

conn.commit()

In [ ]:
cursor.execute("DROP TABLE IF EXISTS order_table")
conn.commit()

cursor.execute("""
CREATE TABLE IF NOT EXISTS order_table (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    menu_name TEXT,
    price INTEGER,
    quantity INTEGER
)
""")
conn.commit()

cursor.execute("INSERT INTO order_table (id, menu_name, price, quantity) VALUES (?, ?, ?, ?)", (1, "Burger", 25, 90))
cursor.execute("INSERT INTO order_table (id, menu_name, price, quantity) VALUES (?, ?, ?, ?)", (2, "Pizza", 30, 80))
cursor.execute("INSERT INTO order_table (id, menu_name, price, quantity) VALUES (?, ?, ?, ?)", (3, "Chai", 30, 778))

conn.commit()

In [ ]:
cursor.execute("SELECT * FROM order_table")
rows = cursor.fetchall()

for row in rows:
    print(row)

(1, 'Burger', 25, 90)
(2, 'Pizza', 30, 80)
(3, 'Chai', 30, 778)

In [ ]:
cursor.execute("SELECT * FROM menu")
rows = cursor.fetchall()

for row in rows:
    print(row)

(1, 'Burger', 25)
(2, 'Pizza', 30)
(3, 'Chai', 30)

In [ ]:
import pandas as pd

df = pd.read_sql_query("SELECT * FROM order_table", conn)
df

   id menu_name  price  quantity
0   1    Burger     25        90
1   2     Pizza     30        80
2   3      Chai     30       778